server:
  port: 8003

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1/captcha?autoReconnect=true&useSSL=false
    username: captcha
    password: captcha

service:
  captcha:
    url: https://kyfw.12306.cn/passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&1543558363631&callback=jQuery19104340823452365097_1543558357966&_=1543558357968
    fetchUrl: fetch
    imageUrl: ${service.captcha.fetchUrl}/ori/
    textUrl: ${service.captcha.fetchUrl}/text/
    cleanUrl: ${service.captcha.fetchUrl}/clean/
    fetchNum: 30

